=== AntonioCrespo2605/1DAM/LM/Ejes4_5_6/6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema">

<xsd:element name="pelis">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="peli" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:element name="peli">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="titulo" type="xsd:string"/>
			<xsd:element name="titulo_original" type="xsd:string" minOccurs="0"/>
			<xsd:element ref="clasificacion" minOccurs="0"/>
			<xsd:element name="fichero_grafico" type="xsd:string" minOccurs="0"/>
			<xsd:element name="anho" type="xsd:gYear" default="2003"/>
			<xsd:element ref="reparto"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:element name="clasificacion">
	<xsd:simpleType>
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:enumeration value="8"/>
			<xsd:enumeration value="12"/>
			<xsd:enumeration value="16"/>
			<xsd:enumeration value="18"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:element>

<xsd:element name="reparto">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="actor" type="xsd:string" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

</xsd:schema>

=== AntonioCrespo2605/1DAM/LM/Ejes4_5_6/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<pelis xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="6.xsd">
	<peli>
		<titulo>titulo en espanish</titulo>
		<titulo_original>titulo original</titulo_original>
		<clasificacion>18</clasificacion>
		<anho>2002</anho>
		<reparto>
			<actor>uno cualquiera</actor>
		</reparto>
	</peli>
		
	<peli>
		<titulo>Torrente, el brazo tonto de la ley</titulo>
		<fichero_grafico>./foto1.png</fichero_grafico>
		<anho>1998</anho>
		<reparto>
			<actor>Santiago Segura</actor>
		</reparto>
	</peli>
</pelis>
